# Generated by Django 5.1.15 on 2026-07-29 09:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organization", "0002_membershipmodel_invited_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=120)),
                ("last_name", models.CharField(max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, default="", max_length=40)),
                ("company", models.CharField(blank=True, default="", max_length=200)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WEB_FORM", "Web Form"),
                            ("REFERRAL", "Referral"),
                            ("COLD_CALL", "Cold Call"),
                            ("EMAIL", "Email"),
                            ("SOCIAL_MEDIA", "Social Media"),
                            ("PARTNER", "Partner"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("CONTACTED", "Contacted"),
                            ("QUALIFIED", "Qualified"),
                            ("CONVERTED", "Converted"),
                            ("DISQUALIFIED", "Disqualified"),
                            ("RECYCLED", "Recycled"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("score", models.IntegerField(default=0)),
                ("owner_id", models.UUIDField(blank=True, null=True)),
                ("assigned_to_id", models.UUIDField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("disqualification_reason", models.TextField(blank=True, default="")),
                ("converted_at", models.DateTimeField(blank=True, null=True)),
                ("converted_to_contact_id", models.UUIDField(blank=True, null=True)),
                (
                    "converted_to_opportunity_id",
                    models.UUIDField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="organization.organizationmodel",
                    ),
                ),
            ],
            options={
                "db_table": "lead_management_leads",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "status"],
                        name="lead_manage_organiz_a4c940_idx",
                    ),
                    models.Index(
                        fields=["organization", "email"],
                        name="lead_manage_organiz_310d90_idx",
                    ),
                    models.Index(
                        fields=["organization", "assigned_to_id"],
                        name="lead_manage_organiz_34dd11_idx",
                    ),
                    models.Index(
                        fields=["organization", "created_at"],
                        name="lead_manage_organiz_df2872_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("score__gte", 0), ("score__lte", 100)),
                        name="ck_lead_score_range",
                    )
                ],
            },
        ),
    ]
