# Generated by Django 5.1.15 on 2026-07-29 09:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leadmanagement", "0001_init_lead_management"),
        ("organization", "0002_membershipmodel_invited_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadStageModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("order", models.IntegerField(default=0)),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                ("is_terminal", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "lead_management_stages",
                "ordering": ["order"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="leadmodel",
            name="ck_lead_score_range",
        ),
        migrations.AlterField(
            model_name="leadmodel",
            name="status",
            field=models.CharField(default="NEW", editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name="leadstagemodel",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_stages",
                to="organization.organizationmodel",
            ),
        ),
        migrations.AddField(
            model_name="leadmodel",
            name="stage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="leadmanagement.leadstagemodel",
            ),
        ),
        migrations.AddIndex(
            model_name="leadmodel",
            index=models.Index(
                fields=["organization", "stage"], name="lead_manage_organiz_4f6217_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="leadstagemodel",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="uq_lead_stage_org_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="leadstagemodel",
            constraint=models.UniqueConstraint(
                fields=("organization", "order"), name="uq_lead_stage_org_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="leadmodel",
            constraint=models.CheckConstraint(
                name="ck_lead_score_range",
                condition=models.Q(score__gte=0, score__lte=100),
            ),
        ),
    ]
