# Generated by Django 5.1.15 on 2026-07-29 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leadmanagement", "0002_lead_pipeline_stages"),
        ("organization", "0002_membershipmodel_invited_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PipelineModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lead_management_pipelines",
                "ordering": ["name"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="leadmodel",
            name="ck_lead_score_range",
        ),
        migrations.AddField(
            model_name="pipelinemodel",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lead_pipelines",
                to="organization.organizationmodel",
            ),
        ),
        migrations.AddField(
            model_name="leadmodel",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="leadmanagement.pipelinemodel",
            ),
        ),
        migrations.AddField(
            model_name="leadstagemodel",
            name="pipeline",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stages",
                to="leadmanagement.pipelinemodel",
            ),
        ),
        migrations.AddConstraint(
            model_name="pipelinemodel",
            constraint=models.UniqueConstraint(
                fields=("organization", "name"), name="uq_pipeline_org_name"
            ),
        ),
    ]
