# Generated by Django 5.1.15 on 2026-07-29 10:06

import uuid

from django.db import migrations


def bootstrap_default_pipelines(apps, schema_editor):
    PipelineModel = apps.get_model("leadmanagement", "PipelineModel")
    LeadStageModel = apps.get_model("leadmanagement", "LeadStageModel")
    LeadModel = apps.get_model("leadmanagement", "LeadModel")

    org_ids = set()
    for sid, in LeadStageModel.objects.values_list("organization_id").distinct():
        org_ids.add(sid)
    for oid, in LeadModel.objects.values_list("organization_id").distinct():
        org_ids.add(oid)

    for org_id in org_ids:
        pipeline = PipelineModel.objects.create(
            id=uuid.uuid4(),
            organization_id=org_id,
            name="Sales Pipeline",
            description="Default sales pipeline",
        )
        LeadStageModel.objects.filter(organization_id=org_id, pipeline__isnull=True).update(pipeline=pipeline)
        LeadModel.objects.filter(organization_id=org_id, pipeline__isnull=True).update(pipeline=pipeline)


class Migration(migrations.Migration):
    dependencies = [
        ("leadmanagement", "0003_lead_pipelines"),
    ]

    operations = [
        migrations.RunPython(bootstrap_default_pipelines, reverse_code=migrations.RunPython.noop),
    ]
