# Generated by Django 5.1.15 on 2026-07-29 10:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leadmanagement", "0004_bootstrap_default_pipelines"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunicationLogModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EMAIL", "Email"),
                            ("WHATSAPP", "WhatsApp"),
                            ("CALL", "Call"),
                            ("SMS", "SMS"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("OUTBOUND", "Outbound"), ("INBOUND", "Inbound")],
                        default="OUTBOUND",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                (
                    "from_address",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "to_address",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("status", models.CharField(default="PENDING", max_length=30)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="leadmanagement.leadmodel",
                    ),
                ),
            ],
            options={
                "db_table": "lead_management_communications",
                "ordering": ["-created_at"],
            },
        ),
    ]
