# Generated by Django 5.1.15 on 2026-07-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leadmanagement", "0005_lead_communications"),
        ("organization", "0002_membershipmodel_invited_by_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="leadstagemodel",
            name="uq_lead_stage_org_name",
        ),
        migrations.RemoveConstraint(
            model_name="leadstagemodel",
            name="uq_lead_stage_org_order",
        ),
        migrations.AddConstraint(
            model_name="leadstagemodel",
            constraint=models.UniqueConstraint(
                fields=("pipeline", "name"), name="uq_lead_stage_pipeline_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="leadstagemodel",
            constraint=models.UniqueConstraint(
                fields=("pipeline", "order"), name="uq_lead_stage_pipeline_order"
            ),
        ),
    ]
