# Generated by Django 5.1.15 on 2026-07-29 11:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leadmanagement", "0006_fix_stage_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLogModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("LEAD_CREATED", "Lead Created"),
                            ("STATUS_CHANGED", "Status Changed"),
                            ("STAGE_CHANGED", "Stage Changed"),
                            ("SCORE_CHANGED", "Score Changed"),
                            ("LEAD_ASSIGNED", "Lead Assigned"),
                            ("COMMUNICATION", "Communication"),
                            ("NOTE_ADDED", "Note Added"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="leadmanagement.leadmodel",
                    ),
                ),
            ],
            options={
                "db_table": "lead_management_activity_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
