# Generated by Django 5.1.15 on 2026-07-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Active"),
                    ("SUSPENDED", "Suspended"),
                    ("DISABLED", "Disabled"),
                ],
                default="ACTIVE",
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="tenantmodel",
            index=models.Index(fields=["organization_id"], name="idx_tenant_org"),
        ),
        migrations.AddIndex(
            model_name="tenantmodel",
            index=models.Index(fields=["status"], name="idx_tenant_status"),
        ),
    ]
