# Generated by Django 5.1.15 on 2026-07-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipmodel",
            name="invited_by",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmodel",
            name="created_by",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationmodel",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="membershipmodel",
            index=models.Index(fields=["user_id"], name="idx_memberships_user"),
        ),
        migrations.AddIndex(
            model_name="membershipmodel",
            index=models.Index(fields=["organization"], name="idx_memberships_org"),
        ),
        migrations.AddIndex(
            model_name="organizationmodel",
            index=models.Index(fields=["slug"], name="idx_orgs_slug"),
        ),
        migrations.AddIndex(
            model_name="organizationmodel",
            index=models.Index(fields=["status"], name="idx_orgs_status"),
        ),
    ]
