# Generated by Django 5.1.15 on 2026-07-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0002_passwordresettoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
